### ISSUE TITLE
🐛 RulesGPT is not functioning

### ISSUE THREAD

**Issue by pierssinclairssw** [SSWConsulting/SSW.Rules.GPT#156]
Cc:

Hi @JackDevAU 

### Describe the Bug

RulesGPT doesn't work at all

### To Reproduce
1. Go to RulesGPT
2. Submit a prompt
3. Unexpected error occurs (both logged in and logged out

### Expected Behavior

RulesGPT works

### Tasks
- [ ] Investigate
- [ ] Fix

### Screenshots

![image](https://github.com/SSWConsulting/SSW.Rules.GPT/assets/79821522/29f94f6a-f511-42b3-b316-aea08a0502c8)
**Figure: The Error**

Thanks!

**Comment by JackDevAU** [comment]
--- Update --- 

I've got the project running locally and everything is working correctly... 🙃🙃🙃🙃🙃

Looking into,

- [ ] AppInsights - something about a socket connection issue (maybe related to https://github.com/SSWConsulting/SSW.Rules.GPT/issues/155)
- [ ] CORS ? 
- [ ] Build pipeline?

**Comment by JackDevAU** [comment]
CC: @pierssinclairssw @ncn-ssw @adamcogan 

Done - With the help of @MattParkerDev, replacing the database connection manually fixed it. 

This has removed the KeyVault reference and instead uses the connection string directly. (This is a temp fix for the moment) 

We found that the issue was from KV not updating the database connection string. 
Creating a new issue for this: https://github.com/SSWConsulting/SSW.Rules.GPT/issues/157
